version: '3'
services:
  ros_noetic:
    image: ros:noetic-ros-core-focal
    container_name: ros_noetic_core
    privileged: true
    volumes:
      - ./your_ros_project:/ros_workspace # Map your ROS project directory to the container
      - ./docker-entrypoint.sh:/ros_entrypoint.sh # Mount the entrypoint script
      - /dev:/dev # Mount the /dev directory to the container, for ODrive USB access
    environment:
      - UDEV=on
    networks:
      - ros_network
    # devices:
      # - "/dev/tty.usbmodem3838345835391:/dev/ttyODrive"
    entrypoint: ["/ros_entrypoint.sh"]
    command: tail -f /dev/null
networks:
  ros_network:
